version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    environment:
      SERVICE_NAME: 'member'
      IMAGE_NAME: 'frontend-member'
      DOCKER_ADDRESS: 'ns1ghter-docker.jfrog.io'
      DOCKER_EMAIL: 'build@ns1ghter.com'
      DOCKER_USER : 'nandab'
      DOCKER_PASS : 'z%9e^pAYvwi4C2d1'
    working_directory: ~/my-project
    steps:
      - checkout
      - run:
          name: Docker & NPM Config
          command: |
            curl -u$DOCKER_USER:$DOCKER_PASS https://ns1ghter.jfrog.io/ns1ghter/api/npm/auth > ~/.npmrc
            curl -u$DOCKER_USER:$DOCKER_PASS https://ns1ghter.jfrog.io/ns1ghter/api/npm/npm/auth/frontend >> ~/.npmrc
            npm config set registry https://ns1ghter.jfrog.io/ns1ghter/api/npm/npm
            npm config set @frontend:registry https://ns1ghter.jfrog.io/ns1ghter/api/npm/npm
      - run:
          name: Install Dependencies
          command: |
            npm install
            curl -O https://storage.googleapis.com/kubernetes-release/release/v1.5.2/bin/linux/amd64/kubectl && chmod +x kubectl
      - run:
          name: Unit Tests
          command: |
            # - npm run lint
            # - npm run flow
            # - npm run test
            kubectl version
            echo $CIRCLE_BRANCH testing
      - run:
          name: Store Test Coverage
          command: |
            # - mkdir -p $CIRCLE_ARTIFACTS/coverage
            # - mv coverage/lcov-report $CIRCLE_ARTIFACTS/coverage/lcov-report
  deploy-master:
    docker:
      - image: circleci/node:6
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Staging
          command: kubectl version
          
  deploy-prod:
    docker:
      - image: circleci/node:6
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: echo $CIRCLE_BRANCH

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-master:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: test
      - deploy-stag:
          requires:
            - build
          filters:
            branches:
              only: staging       
      - deploy-prod-dr:
          requires:
            - build
          filters:
            branches:
              only: production-dr
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: production                     