version: 2.0
jobs:
 build:
   # pre-built images: https://circleci.com/docs/2.0/circleci-images/
   docker:
     - image: circleci/node:6-browsers
   steps:
     - checkout
     - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo $KEY_PASS
     - run:
         name: Running in a Unique Container
         command: |
           node -v