version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/my-project

    steps:
      - checkout
      - run: |
          echo $TEST_REPORTS ${CIRCLE_BRANCH}
  deploy-stage:
    docker:
      - image: circleci/node:6
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Staging
          command: echo ${CIRCLE_BRANCH}          
          
  deploy-prod:
    docker:
      - image: circleci/node:6
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: echo ${CIRCLE_BRANCH}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-master:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: test
      - deploy-stag:
          requires:
            - build
          filters:
            branches:
              only: staging       
      - deploy-prod-dr:
          requires:
            - build
          filters:
            branches:
              only: production-dr
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: production                     