version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/my-project

    steps:
      - checkout

      - run:
          command: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts

      # Create Postgres users and database
      # Note the YAML heredoc '|' for nicer formatting
      - run: |
          sudo $TEST_REPORTS
  deploy-stage:
    docker:
      - image: circleci/node:6
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Staging
          command: echo $BRANCH          
          
  deploy-prod:
    docker:
      - image: circleci/node:6
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: echo $BRANCH

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: test
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master       